// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgJ4tWeIXNq4Qz2-Z7JPStExfVEurDpc',
    appId: '1:305388884169:web:5e48a5bda08b6c9de9bd18',
    messagingSenderId: '305388884169',
    projectId: 'crypto-currencies-list',
    authDomain: 'crypto-currencies-list.firebaseapp.com',
    storageBucket: 'crypto-currencies-list.appspot.com',
    measurementId: 'G-61655ZXEWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLQM0Upv9O6G3BtJs-CIFGD8fjDYBnkM',
    appId: '1:305388884169:android:63d7f58a37ee2c7ae9bd18',
    messagingSenderId: '305388884169',
    projectId: 'crypto-currencies-list',
    storageBucket: 'crypto-currencies-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABuylR7iP32GqO8Kf8bjabzcqIQkf_TN0',
    appId: '1:305388884169:ios:9b505acae4c3a7c7e9bd18',
    messagingSenderId: '305388884169',
    projectId: 'crypto-currencies-list',
    storageBucket: 'crypto-currencies-list.appspot.com',
    iosClientId: '305388884169-5ibo6ou51drhm0a69o33gh4rod065e68.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoCurenciesList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABuylR7iP32GqO8Kf8bjabzcqIQkf_TN0',
    appId: '1:305388884169:ios:9b505acae4c3a7c7e9bd18',
    messagingSenderId: '305388884169',
    projectId: 'crypto-currencies-list',
    storageBucket: 'crypto-currencies-list.appspot.com',
    iosClientId: '305388884169-5ibo6ou51drhm0a69o33gh4rod065e68.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoCurenciesList',
  );
}
